#!/usr/bin/env bash
#install haproxy as load balancer and configure it to direct traffic

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
 sudo sed -i "$ a\listen load_balancer 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption forwardfor\n\toption httpclose\n\tserver 14231-web-01 44.200.178.214:80 check\n\tserver 14231-web-02 35.174.60.115:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
